//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practical1.Model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoryTable
    {
        public int Id { get; set; }
        public Nullable<int> ReferenceId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Title { get; set; }
        public Nullable<bool> Completed { get; set; }
        public string Action { get; set; }
    }
}
