//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practical1.Model.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Practical1Entities : DbContext
    {
        public Practical1Entities()
            : base("name=Practical1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EvenTable> EvenTables { get; set; }
        public virtual DbSet<OddTable> OddTables { get; set; }
        public virtual DbSet<HistoryTable> HistoryTables { get; set; }
    }
}
